apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: financecontrolinator-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: financecontrolinator-{{ .Release.Name }}
    spec:
      containers:
      - name: financecontrolinator-{{ .Release.Name }}
        image: {{ .Values.image }}
        env:
          - name: "ConnectionStrings__InvoicesDbConnection"
            value: http://{{ .Release.Name }}-db-srv:8080
          - name: "ConnectionStrings__InvoicesDbName"
            value: Invoices
          - name: RabbitMq__Host
            value: {{.Values.rabbit.host}}
          - name: RabbitMq__Password 
            value: {{.Values.rabbit.password}}
          - name: RabbitMq__Username 
            value: {{.Values.rabbit.username}}
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-srv
spec:
  selector:
    app: financecontrolinator-{{ .Release.Name }}
  ports:
    - name: financecontrolinator-port
      protocol: TCP
      port: 80
      targetPort: 80

      