name: Publish Expenses coverage to Codacy

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'Microservices/Expenses/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Microservices/Expenses/Expenses.Tests/Expenses.Tests.csproj
    - name: Build
      run: dotnet build Microservices/Expenses/Expenses.Tests/Expenses.Tests.csproj --no-restore
    - name: Test
      run: dotnet test Microservices/Expenses/Expenses.Tests/Expenses.Tests.csproj --no-build --verbosity normal
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./Microservices/Expenses/Expenses.Tests/coverage.opencover.xml
